// ── Shared data (server-side copy) ──────────────────────────
export type Package = {
  slug: string; name: string; type: string
  region: 'Domestic' | 'International'
  destination: string; country: string; duration: string
  price: number; discountPrice: number; rating: number; reviews: number
  image: string; highlights: string[]; inclusions: string[]; exclusions: string[]
  itinerary: { day: number; title: string; description: string }[]
  faqs: { q: string; a: string }[]
  featured?: boolean
}

export const packages: Package[] = [
  { slug: 'maldives-luxury-escape', name: 'Maldives Luxury Overwater Escape', type: 'Honeymoon', region: 'International', destination: 'Maldives', country: 'Maldives', duration: '5 Days / 4 Nights', price: 185000, discountPrice: 149000, rating: 4.9, reviews: 214, image: '/images/hero-maldives.png', featured: true, highlights: ['Private overwater villa', 'Sunset dolphin cruise', 'Candlelight beach dinner', 'Snorkeling'], inclusions: ['4 nights villa', 'Breakfast & dinner', 'Speedboat transfers', 'Seaplane'], exclusions: ['International airfare', 'Travel insurance', 'Personal expenses', 'Visa'], itinerary: [{day:1,title:'Arrival',description:'Arrive at Malé, seaplane transfer.'},{day:2,title:'Island Bliss',description:'Villa & snorkeling.'},{day:3,title:'Adventure',description:'Water sports & spa.'},{day:4,title:'Explore',description:'Local island visit.'},{day:5,title:'Departure',description:'Transfer to Malé.'}], faqs: [{q:'Is this good for honeymooners?',a:'Absolutely.'},{q:'Are flights included?',a:'No, but we can arrange.'}] },
  { slug: 'bali-island-paradise', name: 'Bali Island Paradise', type: 'Family', region: 'International', destination: 'Bali', country: 'Indonesia', duration: '6 Days / 5 Nights', price: 98000, discountPrice: 79000, rating: 4.8, reviews: 178, image: '/images/dest-bali.png', featured: true, highlights: ['Ubud rice terraces', 'Private pool villa', 'Water sports', 'Balinese dinner show'], inclusions: ['5 nights', 'Breakfast', 'Guided tours', 'Transfers'], exclusions: ['Airfare', 'Lunch & dinner', 'Visa', 'Personal expenses'], itinerary: [{day:1,title:'Arrival',description:'Hotel & Seminyak.'},{day:2,title:'Ubud',description:'Rice terraces.'},{day:3,title:'Water',description:'Nusa Dua.'},{day:4,title:'Islands',description:'Nusa Penida.'},{day:5,title:'Leisure',description:'Spa & sunset.'},{day:6,title:'Departure',description:'Airport.'}], faqs: [{q:'Is Bali family-friendly?',a:'Yes, for all ages.'}] },
  { slug: 'swiss-alps-grand-tour', name: 'Swiss Alps Grand Tour', type: 'Luxury', region: 'International', destination: 'Switzerland', country: 'Switzerland', duration: '8 Days / 7 Nights', price: 265000, discountPrice: 229000, rating: 4.9, reviews: 132, image: '/images/dest-switzerland.png', featured: true, highlights: ['Glacier Express', 'Jungfraujoch', 'Lake Lucerne', 'Mount Titlis'], inclusions: ['7 nights', 'Breakfast', 'Swiss Travel Pass', 'City tours'], exclusions: ['Airfare', 'Lunch & dinner', 'Schengen visa', 'Personal'], itinerary: [{day:1,title:'Zurich',description:'City walk.'},{day:2,title:'Lucerne',description:'Lake cruise.'},{day:3,title:'Titlis',description:'Cable car.'},{day:4,title:'Interlaken',description:'Adventure.'},{day:5,title:'Jungfraujoch',description:'Top of Europe.'},{day:6,title:'Glacier Express',description:'Scenic train.'},{day:7,title:'Zermatt',description:'Matterhorn.'},{day:8,title:'Departure',description:'Airport.'}], faqs: [{q:'Is Swiss Travel Pass included?',a:'Yes.'}] },
  { slug: 'dubai-luxury-getaway', name: 'Dubai Luxury Getaway', type: 'Group', region: 'International', destination: 'Dubai', country: 'UAE', duration: '5 Days / 4 Nights', price: 89000, discountPrice: 72000, rating: 4.7, reviews: 256, image: '/images/dest-dubai.png', highlights: ['Burj Khalifa', 'Desert safari', 'Marina cruise', 'Abu Dhabi'], inclusions: ['4 nights', 'Breakfast', 'Desert safari', 'City tours'], exclusions: ['Airfare', 'UAE visa', 'Lunch & dinner', 'Optional tours'], itinerary: [{day:1,title:'Arrival',description:'Marina cruise.'},{day:2,title:'City',description:'Burj & Palm.'},{day:3,title:'Safari',description:'Desert & BBQ.'},{day:4,title:'Abu Dhabi',description:'Mosque.'},{day:5,title:'Departure',description:'Shopping.'}], faqs: [{q:'Visa assistance?',a:'Yes.'}] },
  { slug: 'kerala-backwaters-bliss', name: 'Kerala Backwaters Bliss', type: 'Family', region: 'Domestic', destination: 'Kerala', country: 'India', duration: '6 Days / 5 Nights', price: 42000, discountPrice: 34000, rating: 4.8, reviews: 312, image: '/images/dest-kerala.png', featured: true, highlights: ['Houseboat', 'Munnar tea', 'Kathakali', 'Spice tour'], inclusions: ['5 nights incl. houseboat', 'Breakfast', 'Transfers', 'Sightseeing'], exclusions: ['Airfare', 'Lunch & dinner', 'Entry fees', 'Personal'], itinerary: [{day:1,title:'Kochi',description:'Heritage walk.'},{day:2,title:'Munnar',description:'Tea gardens.'},{day:3,title:'Munnar',description:'Park & museum.'},{day:4,title:'Thekkady',description:'Wildlife.'},{day:5,title:'Alleppey',description:'Houseboat.'},{day:6,title:'Departure',description:'Kochi.'}], faqs: [{q:'Private houseboat?',a:'Yes.'}] },
  { slug: 'rajasthan-royal-heritage', name: 'Rajasthan Royal Heritage', type: 'Luxury', region: 'Domestic', destination: 'Rajasthan', country: 'India', duration: '7 Days / 6 Nights', price: 58000, discountPrice: 47000, rating: 4.7, reviews: 198, image: '/images/dest-rajasthan.png', highlights: ['Amber Fort', 'Lake Palace', 'Desert camp', 'Heritage haveli'], inclusions: ['6 nights heritage', 'Breakfast', 'AC transport', 'Guided tours'], exclusions: ['Airfare', 'Lunch & dinner', 'Monument fees', 'Camel ride'], itinerary: [{day:1,title:'Jaipur',description:'City Palace.'},{day:2,title:'Amber',description:'Fort tour.'},{day:3,title:'Pushkar',description:'Brahma temple.'},{day:4,title:'Udaipur',description:'Lakes.'},{day:5,title:'Jodhpur',description:'Blue city.'},{day:6,title:'Jaisalmer',description:'Desert camp.'},{day:7,title:'Departure',description:'Onward.'}], faqs: [{q:'Heritage hotels?',a:'Yes.'}] },
  { slug: 'goa-beach-retreat', name: 'Goa Beach Retreat', type: 'Group', region: 'Domestic', destination: 'Goa', country: 'India', duration: '4 Days / 3 Nights', price: 28000, discountPrice: 21000, rating: 4.6, reviews: 421, image: '/images/dest-goa.png', highlights: ['Beaches', 'Sunset cruise', 'Water sports', 'Beach resort'], inclusions: ['3 nights resort', 'Breakfast', 'Sightseeing', 'Transfers'], exclusions: ['Airfare', 'Lunch & dinner', 'Water sports', 'Entry tickets'], itinerary: [{day:1,title:'Arrival',description:'Beach relax.'},{day:2,title:'North Goa',description:'Baga & Fort.'},{day:3,title:'South Goa',description:'Colva & cruise.'},{day:4,title:'Departure',description:'Airport.'}], faqs: [{q:'Good for groups?',a:'Yes.'}] },
  { slug: 'thailand-island-hopper', name: 'Thailand Island Hopper', type: 'Group', region: 'International', destination: 'Thailand', country: 'Thailand', duration: '6 Days / 5 Nights', price: 76000, discountPrice: 61000, rating: 4.7, reviews: 289, image: '/images/dest-thailand.png', highlights: ['Phi Phi islands', 'Bangkok temples', 'Phuket beaches', 'Cooking class'], inclusions: ['5 nights', 'Breakfast', 'Island tours', 'Transfers'], exclusions: ['Airfare', 'Visa', 'Lunch & dinner', 'Optional shows'], itinerary: [{day:1,title:'Bangkok',description:'Arrival.'},{day:2,title:'City',description:'Grand Palace.'},{day:3,title:'Phuket',description:'Beach.'},{day:4,title:'Phi Phi',description:'Snorkeling.'},{day:5,title:'Leisure',description:'Shopping.'},{day:6,title:'Departure',description:'Airport.'}], faqs: [{q:'Visa assistance?',a:'Yes.'}] },
]

export type Destination = {
  slug: string; name: string; country: string; state: string
  region: 'Domestic' | 'International'
  description: string; image: string; bestTime: string
  attractions: string[]; tips: string[]
}

export const destinations: Destination[] = [
  { slug: 'maldives', name: 'Maldives', country: 'Maldives', state: 'Indian Ocean', region: 'International', description: 'A tropical paradise of crystal-clear lagoons, overwater villas and coral reefs.', image: '/images/hero-maldives.png', bestTime: 'November to April', attractions: ['Overwater villas', 'Coral reefs', 'Sandbanks', 'Underwater restaurants'], tips: ['Carry reef-safe sunscreen', 'Book seaplane in advance', 'Respect dress codes'] },
  { slug: 'bali', name: 'Bali', country: 'Indonesia', state: 'Bali Province', region: 'International', description: 'The Island of Gods blends rice terraces, temples, culture and beaches.', image: '/images/dest-bali.png', bestTime: 'April to October', attractions: ['Ubud rice terraces', 'Tanah Lot', 'Nusa Penida', 'Seminyak'], tips: ['Rent a scooter', 'Carry cash', 'Dress modestly at temples'] },
  { slug: 'switzerland', name: 'Switzerland', country: 'Switzerland', state: 'Central Europe', region: 'International', description: 'Snow-capped peaks and scenic railways make Switzerland the crown jewel of Europe.', image: '/images/dest-switzerland.png', bestTime: 'May to September', attractions: ['Jungfraujoch', 'Lake Lucerne', 'Glacier Express', 'Matterhorn'], tips: ['Get Swiss Travel Pass', 'Pack warm layers', 'Trains are on time'] },
  { slug: 'dubai', name: 'Dubai', country: 'UAE', state: 'Emirate of Dubai', region: 'International', description: 'A dazzling city of skyscrapers, golden deserts and world-class entertainment.', image: '/images/dest-dubai.png', bestTime: 'November to March', attractions: ['Burj Khalifa', 'Desert safari', 'Palm Jumeirah', 'Dubai Mall'], tips: ['Dress modestly', 'Stay hydrated', 'Fridays are the local weekend'] },
  { slug: 'kerala', name: 'Kerala', country: 'India', state: 'Kerala', region: 'Domestic', description: "God's Own Country with serene backwaters, tea hills and Ayurveda.", image: '/images/dest-kerala.png', bestTime: 'September to March', attractions: ['Alleppey backwaters', 'Munnar tea', 'Periyar wildlife', 'Fort Kochi'], tips: ['Houseboat stay', 'Sadya meals', 'Carry repellent'] },
  { slug: 'rajasthan', name: 'Rajasthan', country: 'India', state: 'Rajasthan', region: 'Domestic', description: 'The land of kings dazzles with forts, palaces, deserts and heritage.', image: '/images/dest-rajasthan.png', bestTime: 'October to March', attractions: ['Amber Fort', 'Lake Pichola', 'Jaisalmer dunes', 'Mehrangarh Fort'], tips: ['Bargain at markets', 'Sun protection', 'Royal Rajasthani thali'] },
  { slug: 'goa', name: 'Goa', country: 'India', state: 'Goa', region: 'Domestic', description: 'Golden beaches, Portuguese heritage and vibrant nightlife.', image: '/images/dest-goa.png', bestTime: 'November to February', attractions: ['Baga beach', 'Fort Aguada', 'Old Goa churches', 'Sunset cruises'], tips: ['Rent a scooter', 'Fresh seafood', 'Respect beach flags'] },
  { slug: 'paris', name: 'Paris', country: 'France', state: 'Île-de-France', region: 'International', description: 'The City of Light with iconic landmarks, world-class art and cuisine.', image: '/images/dest-paris.png', bestTime: 'April to June, October', attractions: ['Eiffel Tower', 'Louvre', 'Notre-Dame', 'Seine cruise'], tips: ['Book online', 'Learn French phrases', 'Watch for pickpockets'] },
]
